### ISSUE TITLE
Compose the equivalences: ∀ n, 1-paths in FSMG.M 1 ≃ Coxeter ≃ LongCoxeter ≃ Lehmer ≃ Aut (Fin n)

### ISSUE THREAD

**Issue by vikraman** [vikraman/2DTypes#14]

**Comment by JacquesCarette** [comment]
Questions: 
1. is this long chain of equivalences supposed to be as types, or as groupoids?
2. what is our reason to believe that this particular chain is the 'easiest' way to go?
3. is the ultimate goal to prove the "collapsed" version FSMG 1 ≃ UFin ?

**Comment by vikraman** [comment]
I edited the title a bit since it was incorrect.

> Questions:
> 
>     1. is this long chain of equivalences supposed to be as types, or as groupoids?
> 

Each type here is a set, so these are equivalences of sets. The first and the last types are types of 1-paths in a groupoid.

>     2. what is our reason to believe that this particular chain is the 'easiest' way to go?
> 

We needed a presentation of the symmetric group to go from bijections to adjacent transpositions, the coxeter representation is a good choice and seems to work.  

>     3. is the ultimate goal to prove the "collapsed" version FSMG 1 ≃ UFin ?

Yes, we should finally have `FSMG.FSMG 1 ≃ FSMG.M 1  ≃ UFin`, this is an equivalence of groupoids.

Here's a sketch of the equivalences we have so far. 
https://github.com/vikraman/2DTypes/blob/master/Pi%2B/Coxeter/Equiv.agda

**Comment by JacquesCarette** [comment]
So, to my mind, a version of what we want is already proven in https://github.com/JacquesCarette/pi-dual/blob/master/Univalence/SEquivSCPermEquiv.agda (as Setoids) for the representation of permutations as "two line" permutations.  It is true that neither @sabry nor I made much 'noise' about that particular theorem in the ESOP paper, and perhaps we should have emphasized it more.

Your answer to 2 doesn't feel like an answer: why involve adjacent transpositions at all? Some representations of permutations are very 'classical' and really ill-suited for a constructive formalization. They might work well in Lean, but are awkward in Agda.

**Comment by inexxt** [comment]
> So, to my mind, a version of what we want is already proven in https://github.com/JacquesCarette/pi-dual/blob/master/Univalence/SEquivSCPermEquiv.agda (as Setoids) for the representation of permutations as "two line" permutations. It is true that neither @sabry nor I made much 'noise' about that particular theorem in the ESOP paper, and perhaps we should have emphasized it more.


1. Although it's good to have this equivalence, it's not really what we need. The problem is still that SCPerm is on the "finite" side of the chain - the same as Lehmer codes and Aut(Fin n). 

2. The issue is that we want to have a presentation of S_n (in the usual mathematical sense of group presentation). There are not very many handy S_n presentations - as far as I know, the main three are adjacent transpositions, arbitrary transpositions, or shifts. Among these, Coxter presentation has two advantages:
 - The proof is already (almost) done for it
 - We want to connect it to FSMG, and the proof that we are planning to use (from Mac Lane book, reference here https://github.com/vikraman/2DTypes/issues/16 ) is also using Coxeter

**Comment by JacquesCarette** [comment]
Perfect, thank you. I really am trying to catch up, and this is the kind of information that I'm missing. [Note that your 'complete list' link is currently a 404].

**Comment by inexxt** [comment]
You're getting 404 because it links to a private repo and I forgot to add you, sorry. Fixed that now.

**Comment by JacquesCarette** [comment]
Thanks, I can confirm access now.

**Comment by JacquesCarette** [comment]
Hmm, have you looked at Young Tableaux for representations of Sn? https://www.math.arizona.edu/~jeremybooher/expos/young_promys.pdf for example.

I finally re-found the "good" page on Lehmer codes: https://en.wikiversity.org/wiki/Inversion_(discrete_mathematics)

**Comment by inexxt** [comment]
I've heard about it, but not read that much (just some introduction back then) - I will look into that, thanks for the link.
But again, it's only a representation, not a presentation of the group (or am I missing something?).

**Comment by JacquesCarette** [comment]
I wouldn't bother with Young Tableaux right now, as I re-look.  The extra info on Lehmer is probably more useful.
