### ISSUE TITLE
Taskboard for MFPS submission

### ISSUE THREAD

**Issue by vikraman** [vikraman/2DTypes#3]
- [x] Sec 1
- [x] Sec 2
- [x] Sec 3 ( @vikraman )
  - [x] Univalent fibrations
  - [x] Propositional Truncation
  - [x] Univalent sub-universes
  - [x] U[2] is univalent
- [x] Sec 4 ( @DreamLinuxer )
  - [x] Write down the proofs in literate agda?

**Comment by JacquesCarette** [comment]
Are there specific things that still need to be done in sections 1 or 2 (other than editing for style)?

Also, what do we want after section 4?

I can work on this on Wednesday-Thursday of this week, and then in bits and pieces Tuesday-Thursday next week (when I will, strictly speaking, be on vacation).

**Comment by vikraman** [comment]
We finished it!
