### ISSUE TITLE
Is Lemma 5.1 of "Categories of Petri Nets" somehow relevant

### ISSUE THREAD

**Issue by JacquesCarette** [vikraman/2DTypes#45]
https://arxiv.org/abs/2101.04238.  It's about the free symmetric strict monoidal category.

**Comment by vikraman** [comment]
Yes, the free SMC occurs in many places. The oldest construction of it I've found is in [Two-dimensional monad theory](https://www.sciencedirect.com/science/article/pii/0022404989901606), in the section on examples of 2-monads.
