### ISSUE TITLE
Write (or copy) the equivalence Lehmer n ≃ (Fin n ≃ Fin n)

### ISSUE THREAD

**Issue by inexxt** [vikraman/2DTypes#9]

**Comment by vikraman** [comment]
There is a proof here: https://github.com/agda/cubical/blob/master/Cubical/Data/Fin/LehmerCode.agda

**Comment by JacquesCarette** [comment]
Yes!!!!  That is a beautiful proof, with lots of good ways to do things.  PunchIn/PunchOut is particularly nice. Excellent find.
